name    'nextrevision-automysqlbackup'
version '0.2.1'
source 'https://github.com/nextrevision/puppet-automysqlbackup/'
author 'nextrevision'
license 'Apache License, Version 2.0'
summary 'Deploy automysqlbackup via Puppet'
description 'Performs full deployment and configuration of automysqlbackup for Debian/Ubuntu and CentOS hosts.'
project_page 'http://github.com/nextrevision/puppet-automysqlbackup/issues'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
